server:
  port: 8189
  servlet:
    context-path: /schedule

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    #    generate-ddl: true

    hibernate:
      hbm2dll:
        auto: validate
#      ddl-auto: validate

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/schedule_new?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: julia
    password: Julia_julia$1

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

